# Generated by Django 4.1.1 on 2022-09-27 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rename_conformation_code_customuser_confirmation_code_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='newusers',
        ),
    ]
