# Generated by Django 4.1.1 on 2022-09-27 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_customuser_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='MyNewUser',
        ),
    ]
