# Generated by Django 4.1.1 on 2022-09-27 10:56

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_rename_customuser_mynewuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('healthkon_id', models.CharField(max_length=50)),
                ('account_id', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('project_id', models.CharField(max_length=32)),
                ('location_id', models.CharField(max_length=32)),
                ('roleid', models.PositiveSmallIntegerField()),
                ('speciality_id', models.PositiveSmallIntegerField()),
                ('token', models.CharField(max_length=64)),
                ('ehr_token', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=64)),
                ('api_token', models.CharField(max_length=80)),
                ('remember_token', models.CharField(max_length=100)),
                ('confirmation_code', models.CharField(max_length=255)),
                ('uid', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
