# Generated by Django 4.1.1 on 2022-09-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_myuser_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mynewuser',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
