# Generated by Django 4.1.1 on 2022-09-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_mynewuser_managers_alter_myuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='account_id',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='api_token',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='confirmation_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='ehr_token',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='healthkon_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='location_id',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='project_id',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='remember_token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='speciality_id',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='token',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='uid',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
