# Generated by Django 4.1.1 on 2022-09-28 16:46

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_myuser_account_id_alter_myuser_api_token_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mynewuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
