# Generated by Django 4.1.1 on 2022-09-28 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_mynewuser_managers_alter_myuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
            ],
        ),
    ]
